# Generated by Django 3.2.24 on 2024-07-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribers',
            options={'verbose_name_plural': 'Subscribers'},
        ),
        migrations.AlterField(
            model_name='mailcontent',
            name='content',
            field=models.TextField(default='\n \nUnsubscribe: https://hanneles-art-gallery-99fb21934da8.herokuapp.com/newsletter/unsubscribe/'),
        ),
        migrations.AlterField(
            model_name='mailcontent',
            name='subject',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
