# Generated by Django 3.2.24 on 2024-06-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('topic', models.IntegerField(blank=True, choices=[(1, 'Painting'), (2, 'Payment'), (3, 'Delivery'), (4, 'Other')], null=True)),
                ('message', models.TextField(blank=True, max_length=1000, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Contact forms',
                'ordering': ['-date'],
            },
        ),
    ]
