# Generated by Django 3.2.24 on 2024-06-10 11:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-date_created']},
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='blogimage',
            new_name='blog_image',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='date_published',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='blog',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='blog_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='header',
            field=models.CharField(max_length=254, null=True, unique=True),
        ),
    ]
