# Generated by Django 3.2.24 on 2024-06-10 20:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academy', '0002_auto_20240610_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=254, null=True, unique=True)),
                ('slug', models.SlugField(max_length=254, null=True, unique=True)),
                ('introtext', models.TextField()),
                ('bodytext', models.TextField()),
                ('link', models.CharField(blank=True, max_length=254, null=True)),
                ('blog_image', models.ImageField(blank=True, null=True, upload_to='academy_images/')),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('date_created', models.DateField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('category', models.ManyToManyField(to='academy.Category')),
                ('likes', models.ManyToManyField(blank=True, null=True, related_name='blog_like', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
