# Generated by Django 3.2.24 on 2024-06-11 11:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academy', '0003_auto_20240610_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='post_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=254, null=True),
        ),
    ]
