# Generated by Django 3.2.23 on 2024-01-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='artist',
            field=models.CharField(default='Hannele K.', max_length=254),
        ),
    ]
