# Generated by Django 3.2.23 on 2024-01-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20240119_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='format',
            field=models.CharField(choices=[('Portrait', 'Portrait'), ('Landscape', 'Landscape'), ('Square', 'Square')], default='Portrait', max_length=254),
        ),
    ]
