# Generated by Django 3.2.23 on 2024-01-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='format',
            field=models.CharField(choices=[('P', 'Portrait'), ('L', 'Landscape'), ('S', 'Square')], max_length=1),
        ),
    ]
